// <auto-generated />
namespace MoneyLover.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class MLover : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MLover));
        
        string IMigrationMetadata.Id
        {
            get { return "201910241443582_MLover"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
